name: .NET ATM CI pipeline

on:  
  push:  
    branches:  
      - DEV 
  pull_request: 
    branches:  
      - DEV 
  workflow_dispatch:

jobs:  
  build:  
    name: Build and tests 
    runs-on: windows-latest
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v2 

    - name: Setup .NET 
      uses: actions/setup-dotnet@v1 
      with:  
        dotnet-version: '7.0.x' 

    - name: Build 
      run: dotnet build
      working-directory: .

    - name: Run tests 
      run: dotnet test --no-build --configuration Release --verbosity normal
      working-directory: .
